.TH dumpelf "1" "May 2005" "SpankY" "User Commands"
.SH NAME
dumpelf \- manual page for dumpelf
.SH SYNOPSIS
.B dumpelf
\fI<file1> \fR[\fIfile2 fileN \fR...]
.SH DESCRIPTION
* Dump internal ELF structure
.SH OPTIONS
.TP
\fB\-v, \-\-verbose\fR
Be verbose (can be specified more than once)
.TP
\fB\-h\fR, \fB\-\-help\fR
* Print this help and exit
.TP
\fB\-V\fR, \fB\-\-version\fR
* Print version and exit
.PP
.SH "SEE ALSO"
.BR readelf (1),
.SH "AUTHORS"
dumpelf written for Gentoo Linux by <vapier@gentoo>
