.TH "isetdyn" "1" "0.1" "Ned Ludd" ""
.SH "NAME"
.LP 
isetdyn \- 
user-space utility to scan elf files
.SH "SYNTAX"
.LP 
isetdyn [\fIoptions\fP] dir1 dir2 dirN...
.br 
.SH "DESCRIPTION"
isetdyn is a user-space utility to test files for the presance of 3 very distnct things.
.br
\fBa)\fR the file is of type ET_DYN
.br
\fBb)\fR the file has a program interpreter
.br
\fBc)\fR the file contains a symbol for main()
.TP
This program has visible standard output only when the file meets all requirments.
It's intended use is from shell scripts via return values to evaluate if a shared object is strip safe. 
.LP 
.SH "FILES"
.LP 
\fInone\fP 
.SH "ENVIRONMENT VARIABLES"
.LP 
.TP 
none
.SH "EXAMPLES"
.LP 
To run this program the standard way type:
.LP 
isetdyn /bin/ls
.br 

.SH "AUTHORS"
.LP 
isetdyn was written by <solar@gentoo.org>
.BR
.SH "SEE ALSO"
.LP 
chpax(1), gradm(8), isetdyn(1), scanelf(1), scanexec(1)
