.TH "scanelf" "1" "User Commands" "Ned Ludd" "User Commands"
.SH "NAME"
.LP 
scanelf \- 
user-space utility to scan elf files
.SH "SYNTAX"
.LP 
Usage: pspax [options]

user@shell$ pspax
.BR 
.SH "DESCRIPTION"
pspax is a user-space utility that scans the proc directory and list ELF types, as well as thier respctive PaX flags and filenames and attributes. Depending on pspax was compiled it additionaly will display the process running set of caabilities.
.LP 
.SH "OPTIONS"
.TP
\fB\-a, \-\-all\fR
* Show all processes
.TP
\fB\-e, \-\-header\fR
* Print GNU_STACK/PT_LOAD markings
.TP
\fB\-p, \-\-pid\fR
* Process ID/pid #
.TP
\fB\-n, \-\-nx\fR
* Only display w^x processes
.TP
\fB\-w, \-\-wx\fR
* Only display w|x processes
.TP
\fB\-v, \-\-verbose\fR
* Be verbose about executable mappings
.TP
\fB\-B, \-\-nobanner\fR
* Don't display the header
.TP
\fB\-h, \-\-help\fR
* Print this help and exit
.TP
\fB\-V, \-\-version\fR
* Print version and exit
.LP
.SH "FILES"
.LP 
\fI/proc/\fP 
\fI/proc/%d/exe\fP
\fI/proc/%d/stat\fP
\fI/proc/%d/status\fP
\fI/proc/%d/attr/current\fP
\fI/proc/%d/maps\fP
.SH "ENVIRONMENT VARIABLES"
.TP 
\fBPATH\fP
When the program is compiled with capability support those will be listed as well.
.SH "EXAMPLES"
.LP
To run this program the standard way type:
.LP
pspax
.SH "REPORTING BUGS"
Please include as much information as possible (using any available debugging options) and send bug reports to pax-utils <solar@gentoo.org>.
.SH "SEE ALSO"
.BR chpax (1),
.BR paxctl (1),
.BR pspax (1),
.BR gradm (8),
.BR scanelf (1),
.SH "AUTHORS"
scanelf was written by <solar and vapier @gentoo.org>
