.TH "scanexec" "1" "0.1" "Ned Ludd" ""
.SH "NAME"
.LP 
scanexec \- 
user-space utility to scan elf files
.SH "SYNTAX"
.LP 
scanexec [\fIoptions\fP] dir1 dir2 dirN...
.BR 
.SH "DESCRIPTION"
scanexec is a user-space utility to scan and list ELF ET_EXEC files, and optionaly list PaX flags.
.BR
The main use of the scanexec util is to quickly identify which files potentially should to be rebuilt as etdyn.
.LP 
.SH "OPTIONS"
.LP 
.TP 
\fBNote\fR
long options are not supported on all platforms.
.TP 
\fB\-h, \-\-help\fR
Output help information and exit.
.TP 
\fB\-v, \-\-version\fR
Output version information and exit.
.TP 
\fB \-x, \-\-pax\fR
Lists PaX flags for each ELF ET_EXEC file.
.TP 
\fB\-p, \-\-path\fR
Scans paths in order they are listed in the environment $PATH
.TP 
.BR
.SH "FILES"
.LP 
\fInone\fP 
.SH "ENVIRONMENT VARIABLES"
.LP 
.TP 
\fBPATH\fP
When the -p option is used the environment variable PATH will be search and used.
.SH "EXAMPLES"
.LP 
To run this program the standard way type:
.LP 
scanexec -p
scanexec -x
.LP 
Alternativly you can run it like:
.LP 
scanexec -x -p /bin /usr/bin /lib
.BR 

.SH "AUTHORS"
.LP 
scanexec was written by <solar@gentoo.org>
.BR
.SH "REPORTING BUGS"
Please include as much information as possible(using any available debugging options) and send bug reports for pax-utils <solar@gentoo.org>
.BR
.SH "SEE ALSO"
.LP 
chpax(1), gradm(8), isetdyn(1), scanelf(1), scanexec(1)
