#!/bin/bash

. "${0%/*}"/../lib.sh

#
# simple scanelf symbol checks
#
scanelf -qsmain -F'%s %f' "${top_builddir}"/scanelf \
	> "${builddir}"/scanelf.simple
testit scanelf.simple{,.good}



exit ${ret}
